# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: .NET

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true


on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/dotnet.yml" 
  pull_request:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/dotnet.yml" 
      
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    defaults:
      run:
        working-directory: ./src
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./tests/TestResults
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./tests/TestResults/**/coverage.cobertura.xml
        fail_ci_if_error: false
